# Generated by Django 4.2.6 on 2023-10-21 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indigene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_Name', models.CharField(max_length=264, unique=True)),
                ('date_of_Birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_education', models.BooleanField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='censusapp.indigene')),
            ],
        ),
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.BooleanField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adults', to='censusapp.indigene')),
            ],
        ),
    ]
